// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi6Yp5pXyeO0W3N0ItdkZzcW9F7sTybsQ',
    appId: '1:737692136866:web:20e5f5d8eb455ba28b2efb',
    messagingSenderId: '737692136866',
    projectId: 'boombet-f3dba',
    authDomain: 'boombet-f3dba.firebaseapp.com',
    storageBucket: 'boombet-f3dba.firebasestorage.app',
    measurementId: 'G-QQQ704Y34R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDiFxeuZH3dsydoncBEvsSCq30IpYc3zA',
    appId: '1:737692136866:android:92d0c8b58612978d8b2efb',
    messagingSenderId: '737692136866',
    projectId: 'boombet-f3dba',
    storageBucket: 'boombet-f3dba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA34YU4IOP1nN2Q6pK13PGFLNQ4_UvGs00',
    appId: '1:737692136866:ios:c8fd3405543e20408b2efb',
    messagingSenderId: '737692136866',
    projectId: 'boombet-f3dba',
    storageBucket: 'boombet-f3dba.firebasestorage.app',
    iosBundleId: 'com.boombet.app',
  );
}
